# checkov:skip=CKV_K8S_43 "Using tags for now, digest will be added later"
---
namespace: dev
resources:
  - ../base
  - ingress.yaml
images:
  - name: docker.io/nishans0/next-portfolio
    newTag: edge
