---
namespace: prod
resources:
  - ../../base
  - ingress.yaml

nameSuffix: -prod

images:
  - name: docker.io/nishans0/next-portfolio
    newTag: sha-ddd8363a33f4e02f462d809e7211a008060aa89f
patches:
  - path: hpa-patch.yaml
