---
namespace: prod
resources:
  - ../../base
  - ingress.yaml
nameSuffix: -prod
images:
  - name: docker.io/nishans0/next-portfolio
    newTag: sha-7011aaf8df34c7023e8bf12441022cc18eab78cc
patches:
  - path: hpa-patch.yaml
