---
namespace: stage
resources:
  - ../base
  - ingress.yaml
images:
  - name: docker.io/nishans0/next-portfolio
    newTag: sha-1ba78ceb7a7c72f768e20e8225143effc039e22f
patches:
  - target:
      kind: Deployment
      name: next-portfolio
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
