---
namespace: stage
resources:
  - ../../base
nameSuffix: -stage
images:
  - name: docker.io/nishans0/next-portfolio
    newTag: sha-5050f56f624c233bd25e4c2d3b1c1eebdca9181f
patches:
  - path: hpa-patch.yaml
